### ISSUE TITLE
Any way to get it to NOT create alt text in various languages?  

### ISSUE THREAD

**Issue by isaackearl** [21stdigital/statamic-aida#17]
It would be really nice for me if I could configure it as 'en' => 'alt' and leave it at just that.  Is there a way for me to disable the auto creation in other locales?  Really cool package btw.  Thanks!

**Comment by Sm1lEE** [comment]
Hi @isaackearl,

please try this configuration in your `config/aida.php` file:
```php
// config/aida.php

<?php

return [

  // ...

  'alt_field_mapping' => [
    'en' => 'alt'
  ],
  
  // ...

];

?>
```

(Ensure that the configuration file is published first: `php artisan vendor:publish --tag="aida-config"`)

With this configuration A.I.D.A will only generate alt texts for your `en` site and save them on the `alt` field. It will not generate alt texts for any other site/language.

**Comment by isaackearl** [comment]
awesome that totally worked thanks!  Funny part is that I thought I did that yesterday but I must have had a caching issue or something.  I went to record a video today so I could show you the bug, and sure enough it just worked as expected.  Thanks!
