### ISSUE TITLE
API keys not accepted

### ISSUE THREAD

**Issue by tidygraphic** [21stdigital/statamic-aida#32]
After following the installation instructions for the addon I can't get the API keys to work. The site is running Statamic 4.53.2 and I've tried using both Project and User API keys (which is now deprecated). 

### Error with Project key

`Incorrect API key provided: **-*******************************************************. You can find your API key at https://platform.openai.com/account/api-keys.`

### Error with User key

`The model *gpt-4-vision-preview has been deprecated, learn more here: https://platform.openai.com/docs/deprecations`

If you could let me know what I might be missing or if this is an OpenAI account issue (we're using a customer account) that would be great.

**Comment by Sm1lEE** [comment]
Hi @tidygraphic , thank you for your issue. 

We are looking into the issue and will get back to you with a solution.

**Comment by Sm1lEE** [comment]
Hi @tidygraphic ,

version 2 of the Statamic A.I.D.A addon is released (requiring Statamic 5). We recommend using this version for current and future projects.

If this is not suitable for you, there is also a bugfix release 1.0.1 for the older Statamic 4 version available.
